name: Deploy to GitHub Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'SHA of the commit to build and deploy to the "previous" directory'
        required: false

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: npm run build:static

      - name: Deploy to GitHub Pages (main)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./dist/client
          publish_branch: gh-pages
          keep_files: true

  manual-previous-build:
    # Triggered only manually
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.commit_sha != ''
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the specified commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commit_sha }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: npm run build:static
        env:
          VITE_BASE: '/makieta-specteam/previous/'

      - name: Copy index.html to 404.html for SPA routing
        run: cp ./dist/client/index.html ./dist/client/404.html

      - name: Deploy to the 'previous' directory on gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./dist/client
          destination_dir: previous
          publish_branch: gh-pages
          keep_files: true
